language: python

matrix:
  include:
    - python: 3.6
      env: TOX_ENV=py36
    - python: 3.7
      env: TOX_ENV=py37
    - python: 3.7
      env: TOX_ENV=flake8
    - python: 3.7
      env: TOX_ENV=mypy

install:
  - pip install -U setuptools wheel
  - pip install tox

script: tox -e $TOX_ENV
